apiVersion: apps/v1
kind: Deployment
metada:
  name: backend-deployment
  labels:
    app: backend
spec:
  repllicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      container:
        - name: backend
          image: fabianbello/pruebafinal
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
