apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  type: LoadBalancer
  selector:
    app: sonar
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001